# Generated by Django 4.1.3 on 2023-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_inscrito_nombre_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('terminado', 'terminado'), ('en revision', 'en revision'), ('en desarrollo', 'en desarrollo'), ('rechazado', 'rechazado'), ('en correccion', 'en correcion')], default='en revision', max_length=20),
        ),
    ]
