# Generated by Django 4.1.3 on 2023-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('terminado', 'terminado'), ('en revision', 'en revision'), ('en desarrollo', 'en desarrollo'), ('anulado', 'anulado'), ('en correccion', 'en correcion')], default='en revision', max_length=20),
        ),
    ]
